print("Helloooo World..!!")
print("Goodbye Universe..!!")
print("I'm a dumb bunny")
print("There's a rat in the kitchen what am i gonna do..??")
print("Oops, my bad.....")
print("I broke the build")
print("I broke it again")
print("the greatest")
print("monday")
